// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the License for the
// specific language governing permissions and limitations
// under the License.

/*
 * Author: Lars van Leeuwen
 * Code for running a Parquet to Arrow converter for 64 bit primitives on FPGA.
 *
 * Inputs:
 *  parquet_hw_input_file_path: file_path to hardware compatible Parquet file
 *  reference_parquet_file_path: file_path to Parquet file compatible with the
 * standard Arrow library Parquet reading functions. This file should contain
 * the same values as the first file and is used for verifying the hardware
 * output. num_val: How many values to read.
 */

#include <chrono>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <memory>
#include <random>
#include <stdlib.h>
#include <unistd.h>
#include <vector>

// Apache Arrow
#include <arrow/api.h>
#include <arrow/io/api.h>
#include <parquet/arrow/reader.h>
#include <parquet/arrow/writer.h>

// Fletcher
#include "fletcher/api.h"

#ifdef SV_TEST
#include "fletcher_aws_sim.h"
#endif

#define REG_BASE 10

#define PRIM_WIDTH 64

std::shared_ptr<arrow::RecordBatch> prepareRecordBatch(uint32_t num_val) {
  std::shared_ptr<arrow::Buffer> values;

  arrow::Result<std::shared_ptr<arrow::Buffer>> bufResult =
      arrow::AllocateBuffer(sizeof(int64_t) * num_val);
  if (bufResult.ok()) {
    values = bufResult.ValueOrDie();
  } else {
    throw std::runtime_error("Could not allocate values buffer.");
  }

  auto array =
      std::make_shared<arrow::Int64Array>(arrow::int64(), num_val, values);

  //  This function no longer exists, not sure if passing meta data is necessary
  //  auto schema_meta = metaMode(fletcher::Mode::WRITE);
  std::shared_ptr<arrow::Schema> schema = arrow::schema(
      {arrow::field("int", arrow::int64(), false)}); //, schema_meta);

  auto rb = arrow::RecordBatch::Make(schema, num_val, {array});

  return rb;
}

void setPtoaArguments(std::shared_ptr<fletcher::Platform> platform,
                      uint32_t num_val, uint64_t max_size,
                      da_t device_parquet_address) {
  dau_t mmio64_writer;

  platform->WriteMMIO(REG_BASE + 0, num_val);

  mmio64_writer.full = device_parquet_address;
  platform->WriteMMIO(REG_BASE + 1, mmio64_writer.lo);
  platform->WriteMMIO(REG_BASE + 2, mmio64_writer.hi);

  mmio64_writer.full = max_size;
  platform->WriteMMIO(REG_BASE + 3, mmio64_writer.lo);
  platform->WriteMMIO(REG_BASE + 4, mmio64_writer.hi);

  return;
}

void checkMMIO(std::shared_ptr<fletcher::Platform> platform, uint32_t num_val) {
  uint32_t value32;

  platform->ReadMMIO(REG_BASE + 0, &value32);

  std::cout << "MMIO num_val=" << value32 << ", should be " << num_val
            << std::endl;

  for (int i = 0; i < 15; i++) {
    platform->ReadMMIO(i, &value32);
  }
}

// Use standard Arrow library functions to read Arrow array from Parquet file
// Only works for Parquet version 1 style files.
std::shared_ptr<arrow::ChunkedArray> readArray(std::string hw_input_file_path) {
  std::shared_ptr<arrow::io::ReadableFile> infile;
  arrow::Result<std::shared_ptr<arrow::io::ReadableFile>> result =
      arrow::io::ReadableFile::Open(hw_input_file_path);
  if (result.ok()) {
    infile = result.ValueOrDie();
  } else {
    printf("Error opening Parquet file: code %d, error message: %s\n",
           (int)result.status().code(), result.status().message().c_str());
    exit(-1);
  }

  std::unique_ptr<parquet::arrow::FileReader> reader;
  parquet::arrow::OpenFile(infile, arrow::default_memory_pool(), &reader);

  std::shared_ptr<arrow::ChunkedArray> array;
  reader->ReadColumn(0, &array);

  return array;
}

#ifdef SV_TEST

// fw decl
int tpch_main(int argc, char **argv);
extern "C" void test_main(uint32_t *exit_code) {

  printf("tpch.cpp test_main simulation runtime entry point\n");

  char *rb_base = getenv("TEST_RECORDBATCH_BASE");
  if (rb_base) {
    // printf("TEST_RECORDBATCH_BASE: %s", rb_base ); //do not try to print this
    // because it is not terminated
  } else {
    printf("Error: TEST_RECORDBATCH_BASE not found.\n");
    printf("Please set this environment variable to the location (including "
           "the path) "
           "of the test recordbatches generated by tpch.py, excluding the "
           "number+extension suffix (000.rb).\n");
    printf("For example: `export "
           "TEST_RECORDBATCH_BASE=~/workspaces/tpch/gen/rematch`.\n");
    exit_code = 0;
    return;
  }

  char *argv[] = {(char *)"tpch", rb_base, (char *)"1", (char *)"2"};
  if (tpch_main(4, argv) == 0) {
    *exit_code = 1;
  } else {
    *exit_code = 0;
  }
}

int tpch_main(int argc, char **argv) {

#else //! SV_TEST
int main(int argc, char **argv) {
#endif
  fletcher::Status status;
  std::shared_ptr<fletcher::Platform> platform;
  std::shared_ptr<fletcher::Context> context;

  fletcher::Timer t;

  const char *hw_input_file_path =
      "/home/yyunon/Datasets/extendedprice100.parquet";
  const char *reference_parquet_file_path =
      "/home/yyunon/Datasets/extendedprice100ref.parquet";
  uint32_t num_val = 100;
  uint64_t file_size;
  uint8_t *file_data;

// if (argc > 3) {
//  hw_input_file_path = argv[1];
//  reference_parquet_file_path = argv[2];
//  num_val = (uint32_t)std::strtoul(argv[3], nullptr, 10);

//} else {
//  std::cerr << "Usage: prim64 <parquet_hw_input_file_path> "
//               "<reference_parquet_file_path> <num_values>"
//            << std::endl;
//  return 1;
//}

// Create a Fletcher platform object, attempting to autodetect the platform.
// Create a Fletcher platform object, attempting to autodetect the platform.
#ifdef SV_TEST
  status = fletcher::Platform::Make("aws_sim", &platform);
#else
  // Create a Fletcher platform object, attempting to autodetect the platform.
  status = fletcher::Platform::Make("aws", &platform);
#endif

  if (!status.ok()) {
    std::cerr << "Could not create Fletcher platform." << std::endl;
    return -1;
  }

  /*************************************************************
   * Parquet file reading
   *************************************************************/

  // Open parquet file
  std::ifstream parquet_file;
  parquet_file.open(hw_input_file_path, std::ifstream::binary);

  if (!parquet_file.is_open()) {
    std::cerr << "Error opening Parquet file" << std::endl;
    return 1;
  }

  // Get filesize
  parquet_file.seekg(0, parquet_file.end);
  file_size = parquet_file.tellg();
  parquet_file.seekg(4, parquet_file.beg); // Skip past Parquet magic number

  // Read file data
  // file_data = (uint8_t*)std::malloc(file_size);
  posix_memalign((void **)&file_data, 4096, file_size - 4);
  parquet_file.read((char *)file_data, file_size - 4);
  unsigned int checksum = 0;
  for (uint64_t i = 0; i < file_size; i++) {
    checksum += file_data[i];
  }
  printf("Parquet file checksum 0x%lu\n", (long unsigned int)checksum);

  /*************************************************************
   * FPGA RecordBatch preparation
   *************************************************************/

  t.start();
  auto arrow_rb_fpga = prepareRecordBatch(num_val);
  t.stop();
  std::cout << "Prepare FPGA RecordBatch         : " << t.seconds()
            << std::endl;
  auto result_array =
      std::dynamic_pointer_cast<arrow::Int64Array>(arrow_rb_fpga->column(0));
  auto result_buffer_raw_data = result_array->values()->mutable_data();
  auto result_buffer_size = result_array->values()->size();
  std::cout << "Result buf. size" << result_buffer_size << "\n";
  /*************************************************************
   * FPGA Initilialization
   *************************************************************/

  // Initialize the platform.
#ifdef SV_TEST
  InitOptions options = {1}; // do not initialize DDR for the 1DDR version
  platform->init_data = &options;
#endif
  platform->Init();

  // Create context and kernel
  fletcher::Context::Make(&context, platform);
  fletcher::Kernel kernel(context);

  t.start();
  kernel.Reset();

  // Setup destination recordbatch on device
  context->QueueRecordBatch(arrow_rb_fpga);
  context->Enable();

  // Malloc parquet file on device
  da_t device_parquet_address;
  if (strcmp("oc-accel", platform->name().c_str()) == 0 ||
      strcmp("snap", platform->name().c_str()) == 0) {
    printf("Platform [%s]: Skipping device buffer allocation and host to "
           "device copy.\n",
           platform->name().c_str());
    // Set all the MMIO registers to their correct value
    setPtoaArguments(platform, num_val, file_size, (da_t)(file_data));
  } else {
    platform->DeviceMalloc(&device_parquet_address, file_size);

    // Set all the MMIO registers to their correct value
    setPtoaArguments(platform, num_val, file_size, device_parquet_address);
  }
  t.stop();
  std::cout << "FPGA Initialize                  : " << t.seconds()
            << std::endl;
  checkMMIO(platform, num_val);

  // Make sure all buffer memory is allocated
  memset(result_buffer_raw_data, 0, result_buffer_size);

  /*************************************************************
   * FPGA host to device copy
   *************************************************************/

  t.start();
  platform->CopyHostToDevice(file_data, device_parquet_address, file_size);
  t.stop();
  std::cout << "FPGA host to device copy         : " << t.seconds()
            << std::endl;

  /*************************************************************
   * FPGA processing
   *************************************************************/

  t.start();
  kernel.Start();
  kernel.WaitForFinish(10);
  t.stop();
  std::cout << "FPGA processing time             : " << t.seconds()
            << std::endl;

  /*************************************************************
   * FPGA device to host copy
   *************************************************************/

  t.start();
  platform->CopyDeviceToHost(context->device_buffer(0).device_address,
                             result_buffer_raw_data,
                             sizeof(int64_t) * (num_val));
  t.stop();

  size_t total_arrow_size = sizeof(int64_t) * num_val;

  std::cout << "FPGA device to host copy         : " << t.seconds()
            << std::endl;
  std::cout << "Arrow buffers total size         : " << total_arrow_size
            << std::endl;

  /*************************************************************
   * Check results
   *************************************************************/

  auto correct_array = std::dynamic_pointer_cast<arrow::Int64Array>(
      readArray(std::string(reference_parquet_file_path))->chunk(0));
  if (result_array->Equals(correct_array)) {
    std::cout << "Test passed!" << std::endl;
  } else {
    // sometimes, Equals() thinks it failed but checking the arrays does not
    // show errors std::cout << "Test Failed!" << std::endl;
    int error_count = 0;
    for (int i = 0; i < result_array->length(); i++) {
      if (result_array->Value(i) != correct_array->Value(i)) {
        error_count++;
      }
      if (i < 20) {
        std::cout << result_array->Value(i) << " " << correct_array->Value(i)
                  << std::endl;
      }
    }

    if (result_array->length() != num_val) {
      error_count++;
    }

    if (error_count == 0) {
      std::cout << "Test passed!" << std::endl;
    } else {
      std::cout << "Test failed. Found " << error_count
                << " errors in the output Arrow array" << std::endl;
    }
  }

  std::free(file_data);

  return 0;
}
