# Fletcher files

${CL_ROOT}/design/vhdl/fletcher/vhlib/util/UtilMisc_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/util/UtilInt_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/util/UtilConv_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/Stream_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/interconnect/Interconnect_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/axi/AxiReadConverter.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamArb.vhd
${CL_ROOT}/design/vhdl/fletcher/interconnect/BusReadArbiterVec.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayConfigParse_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayConfig_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/Array_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayReaderStruct.vhd
${CL_ROOT}/design/vhdl/fletcher/buffers/Buffer_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayReaderNull.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayReaderListPrim.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/util/UtilStr_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/interconnect/BusReadBuffer.vhd
${CL_ROOT}/design/vhdl/fletcher/buffers/BufferReaderRespCtrl.vhd
${CL_ROOT}/design/vhdl/fletcher/buffers/BufferReaderResp.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamGearboxSerializer.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamGearboxParallelizer.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamGearbox.vhd
${CL_ROOT}/design/vhdl/fletcher/buffers/BufferReaderPost.vhd
${CL_ROOT}/design/vhdl/fletcher/buffers/BufferReaderCmdGenBusReq.vhd
${CL_ROOT}/design/vhdl/fletcher/buffers/BufferReaderCmd.vhd
${CL_ROOT}/design/vhdl/fletcher/buffers/BufferReader.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayReaderUnlockCombine.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamNormalizer.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayReaderListSyncDecoder.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayReaderListSync.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayReaderList.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayReaderLevel.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayReaderArb.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayReader.vhd
${CL_ROOT}/design/vhdl/fletcher/arrays/ArrayCmdCtrlMerger.vhd
${CL_ROOT}/design/vhdl/fletcher/parallel_patterns/StreamSliceArray.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamElementCounter.vhd
${CL_ROOT}/design/vhdl/fletcher/parallel_patterns/StreamAccumulator.vhd
${CL_ROOT}/design/vhdl/fletcher/parallel_patterns/SequenceStream.vhd
${CL_ROOT}/design/vhdl/fletcher/parallel_patterns/ParallelPatterns_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/parallel_patterns/ReduceStream.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamSync.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/util/UtilRam1R1W.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamFIFOCounter.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/util/UtilRam_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamFIFO.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamBuffer.vhd
${CL_ROOT}/design/vhdl/fletcher/vhlib/stream/StreamSlice.vhd
${CL_ROOT}/design/vhdl/fletcher/axi/Axi_pkg.vhd

${CL_ROOT}/design/vhdl/fletcher/arrow/Arrow_pkg.vhd

${CL_ROOT}/design/vhdl/fletcher/wrapper/Wrapper_pkg.vhd
${CL_ROOT}/design/vhdl/fletcher/wrapper/UserCoreController.vhd

# PTOA files
${CL_ROOT}/design/vhdl/fast-p2a/compression/snappy/Snappy.vhd
${CL_ROOT}/design/vhdl/fast-p2a/compression/snappy/SnappyDecompressor.vhd
${CL_ROOT}/design/vhdl/fast-p2a/ptoa/Ptoa.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/Encoding.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/Delta.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/AdvanceableFiFo.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/BitUnpackerShifter.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/BitUnpacker.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/BlockValuesAligner.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/BlockHeaderReader.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/BlockShiftControl.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/DeltaAccumulatorFV.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/DeltaAccumulatorMD.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/DeltaAccumulator.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/DeltaHeaderReader.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/delta/DeltaDecoder.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/VarIntDecoder.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/DecoderWrapper.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/DecompressorWrapper.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/PreDecBuffer.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/ValBuffer.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/PlainDecoder.vhd
${CL_ROOT}/design/vhdl/fast-p2a/encoding/ValuesDecoder.vhd
${CL_ROOT}/design/vhdl/fast-p2a/thrift/Thrift.vhd
${CL_ROOT}/design/vhdl/fast-p2a/thrift/V2MetadataInterpreter.vhd
${CL_ROOT}/design/vhdl/fast-p2a/alignment/Alignment.vhd
${CL_ROOT}/design/vhdl/fast-p2a/alignment/DataAligner.vhd
${CL_ROOT}/design/vhdl/fast-p2a/alignment/HistoryBuffer.vhd
${CL_ROOT}/design/vhdl/fast-p2a/alignment/ShifterRecombiner.vhd
${CL_ROOT}/design/vhdl/fast-p2a/ingestion/Ingestion.vhd
${CL_ROOT}/design/vhdl/fast-p2a/ingestion/Ingester.vhd
${CL_ROOT}/design/vhdl/fast-p2a/ptoa/ParquetReader.vhd

${CL_ROOT}/design/vhdl/ptoa_wrapper_plain_uncompressed.vhd
${CL_ROOT}/design/vhdl/AxiTop.vhd
